# Spark Connect server(ホスト :15002)— .130 用
# カタログ scalardb_catalog → Analytics Server(minikube NodePort 31051/31052)
spark.jars.packages=com.scalar-labs:scalardb-analytics-spark-all-3.5_2.12:3.18.0
spark.sql.catalog.scalardb_catalog=com.scalar.db.analytics.spark.ScalarDbAnalyticsCatalog
spark.sql.catalog.scalardb_catalog.server.host=192.168.49.2
spark.sql.catalog.scalardb_catalog.server.catalog.port=31051
spark.sql.catalog.scalardb_catalog.server.metering.port=31052
spark.extraListeners=com.scalar.db.analytics.spark.metering.ScalarDbAnalyticsListener
spark.driver.memory=1g
